<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends EntityRepository
{

	public function getCommande()
	{
/*	  $qb = $this
	    ->createQueryBuilder('c')
	    ->Join('c.commercial', 'com')
	    ->addSelect('com.nomContact')
	    ->Join('c.client', 'cli')
	    ->addSelect('cli.nomSociete');

	  return $qb
	    ->getQuery()
	    ->getResult();*/

	  $qb = $this
	    ->createQueryBuilder('c')
	    ->Join('c.commercial', 'com')
	    ->addSelect('com.nomContact')
	    ->Join('c.client', 'cli')
	   	->where('c.type = :type')
	    ->setParameters(array('type'=> 'CD'));

	  return $qb
	    ->getQuery()
	    ->getResult();
	}

	public function getCommandeParSociete($id)
	{

	  $qb = $this
	    ->createQueryBuilder('c')
	    ->Join('c.commercial', 'com')
	    ->addSelect('com.nomContact')
	    ->Join('c.client', 'cli')
	    ->where('cli.idtSociete = :id')
	    ->andWhere('c.type = :type')
	    ->setParameters(array('id'=> $id, 'type' => 'CD'));

	  return $qb
	    ->getQuery()
	    ->getResult();
	}
}
