<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
//use AppBundle\Entity\CommandeProduits;

/**
 * CommandeDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeProduitsRepository extends EntityRepository
{
	public function getDetailsCommande($id)
	{

		$qb = $this->createQueryBuilder('c')
		    ->where('c.commande = :id' )
		    ->setParameters(array('id'=>$id));

		return $qb
		    ->getQuery()
		    ->getResult();
	}
}
