<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
	public function getCommerciaux()
	{
	  return $this
	    ->createQueryBuilder('c')
	    ->join('c.societe', 'soc')
	    ->where('soc.typeSociete = :type')
	    ->andWhere('c.intitulePoste = :nom')
	    ->setParameters(array('type'=> 'M', 'nom' => 'Commercial'));
	}

	public function getContactsParSociete($id)
	{
		/*$qb = $this->_em->createQueryBuilder();

      	$qb->select('c.idtContact')
      	   ->addSelect('c.nomContact')
      	   ->addSelect('c.prenomContact')
      	   ->addSelect('c.email')
      	   ->addSelect('c.telFixe')
      	   ->addSelect('c.utilisateur')
      	   ->from($this->_entityName, 'c')
		   ->where('c.societe = :id' )
		   ->setParameters(array('id'=> $id));*/
		   
		$qb = $this->createQueryBuilder('c')
		   	->where('c.societe = :id' )
		   	->setParameters(array('id'=> $id));

      	return $qb
      		->getQuery()
      		->getResult();
	}

	public function getContactDetails($id)
	{

		$qb = $this->createQueryBuilder('c')
      	   	->where('c.idtContact = :id')
      	   	->setParameters(array('id' => $id));

		return $qb
		    ->getQuery()
		    ->getSingleResult();
	}

	public function getContactParUtilisateur($id)
	{
		return $this->createQueryBuilder('c')
					->leftjoin('c.societe', 'soc')
					->addSelect('soc')
					->where('c.utilisateur = :id')
					->setParameters(array('id' => $id))
					->getQuery()
					->getSingleResult();
	}

}
