<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ListeChaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeChaineRepository extends EntityRepository
{
}
