<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NomenclatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomenclatureRepository extends EntityRepository
{
	
	
	public function getNomenclature($code)
	{
			$qb = $this->createQueryBuilder('n')
			->join('n.produit','produit')
			->addSelect('produit.nomProduit')
			->addSelect('produit.codeProduit')
			->where('n.codeProduit= :id')
			->setParameters(array('id'=> $code));

		return $qb
			->getQuery()
			->getResult();
		
	}
}
