<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends EntityRepository
{
	public function getListeProduits()
	{
	   $qb =  $this->createQueryBuilder('p')
	   	->select('p.idtProduit')
	   	->addSelect('p.codeProduit')
	   	->addSelect('p.nomProduit')
	   	->addSelect('p.descriptionProduit')
	   	->addSelect('p.prixProduit')
	    ->where('p.producteur = :id')
	    ->setParameters(array('id'=> 1));

	   return $qb
	   			->getQuery()
	   			->getResult();
	}
}
