<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
	public function getRoleClient()
	{
		$qb = $this->createQueryBuilder('r')
		    ->where('r.nom = :name' )
		    ->setParameters(array('name' => 'Client'));

		return $qb
		    ->getQuery()
		    ->getResult();
	}

	public function getRoles()
	{
		$qb = $this->createQueryBuilder('r');

		return $qb
		    ->getQuery()
		    ->getResult();
	}
}