<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends EntityRepository
{
	public function getListeStock()
	{
	    $qb =  $this->createQueryBuilder('s')
	   		->leftJoin('s.produit', 'p')
	    	->addSelect('p')
	    	->leftJoin('p.producteur', 'fournisseur')
	    	->addSelect('fournisseur');

	    return $qb
	   		->getQuery()
	   		->getResult();
	}

	public function getLigneStock($id)
	{	
		$qb = $this->createQueryBuilder('s')
	   		->leftJoin('s.produit', 'p')
	    	->addSelect('p')
			->where('s.idtEntree = :id')
			->setParameters(array('id'=> $id));

		return $qb
			->getQuery()
			->getSingleResult();
	}
}
