<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends EntityRepository
{
	public function getListeStock()
	{
	   $qb =  $this->createQueryBuilder('s')
	   		->leftJoin('s.produit', 'p')
	    	->addSelect('p');

	   return $qb
	   		->getQuery()
	   		->getResult();
	}

}
